name: Close OpsGenie Alert
description: Close an OpsGenie Alert
branding:
  icon: 'bell-off'
  color: 'gray-dark'
inputs:
  api_key:
    description: OpsGenie API key
    required: true
  use_eu_url:
    description: Boolean. true if using Opsgenie EU API endpoint
    required: false
    default: 'false'
  alias:
    description: Alias of the alert to close
    required: true
  user:
    description: OpsGenie Actor
    required: false
    default: github-action
  note:
    description: Close alert note
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
