name: Compile

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: rockem/close-opsgenie-alert-action
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '17'

      - name: Compile action
        run: |
          yarn install --frozen-lockfile
          yarn compile

      - name: Commit new index.js
        run: |
          git config --global user.email "eli.segal@gmail.com"
          git config --global user.name "rockem"
          git diff --quiet HEAD || git commit -am "ci:Updated compilation of index.js [skip ci]"
          git push
