name: Compile index.js

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: yarn install
      - run: yarn global add @vercel/ncc

      - name: Compile all into index.js
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: ncc build index.js --license licenses.txt

      - name: Commit new index.js
        run: |
          git config --global user.email "eli.segal@gmail.com"
          git config --global user.name "rockem"
          git diff --quiet HEAD || git commit -am "ci:Updated compilation of index.js [skip ci]"
          git push
